Repository Team-Walkie/Walkie-Server, pull requests merged in 2023-08, with the labels that each got.

#14 팔로우 관련 문제 픽스, 스웨거 일부 작성
  build.gradle
  src/main/java/com/whyranoid/walkie/QuerydslConfig.java
  src/main/java/com/whyranoid/walkie/controller/FollowController.java
  src/main/java/com/whyranoid/walkie/controller/WalkingController.java
  src/main/java/com/whyranoid/walkie/domain/Follow.java
  src/main/java/com/whyranoid/walkie/domain/Walkie.java
  src/main/java/com/whyranoid/walkie/dto/WalkieDto.java
  src/main/java/com/whyranoid/walkie/dto/WalkingDto.java
  src/main/java/com/whyranoid/walkie/dto/request/WalkieStatusChangeRequest.java
  src/main/java/com/whyranoid/walkie/dto/response/WalkieStatusChangeResponse.java
  src/main/java/com/whyranoid/walkie/dto/response/WalkingStartResponse.java
  src/main/java/com/whyranoid/walkie/repository/FollowRepository.java
  src/main/java/com/whyranoid/walkie/repository/HistoryRepository.java
  src/main/java/com/whyranoid/walkie/repository/WalkieRepository.java
  src/main/java/com/whyranoid/walkie/repository/querydsl/FollowRepositoryQuerydsl.java
  src/main/java/com/whyranoid/walkie/repository/querydsl/FollowRepositoryQuerydslImpl.java
  src/main/java/com/whyranoid/walkie/service/FollowService.java
  src/main/java/com/whyranoid/walkie/service/WalkingService.java
Labels: 병희

#15 배지 관련 api 구현
  src/main/java/com/whyranoid/walkie/controller/BadgeController.java
  src/main/java/com/whyranoid/walkie/domain/Badge.java
  src/main/java/com/whyranoid/walkie/domain/BadgeCollection.java
  src/main/java/com/whyranoid/walkie/dto/response/BadgeDto.java
  src/main/java/com/whyranoid/walkie/repository/BadgeRepository.java
  src/main/java/com/whyranoid/walkie/service/BadgeService.java
Labels: api

#17 안드 요청사항 우선반영
  src/main/java/com/whyranoid/walkie/controller/WalkieController.java
  src/main/java/com/whyranoid/walkie/dto/WalkieDto.java
  src/main/java/com/whyranoid/walkie/dto/WalkingDto.java
  src/main/java/com/whyranoid/walkie/dto/response/WalkieSignUpResponse.java
  src/main/java/com/whyranoid/walkie/service/WalkieService.java
Labels: 병희, api

#20 [api] 운동 시작, 실시간 좋아요
  src/main/java/com/whyranoid/walkie/controller/WalkingController.java
  src/main/java/com/whyranoid/walkie/domain/History.java
  src/main/java/com/whyranoid/walkie/domain/WalkingLike.java
  src/main/java/com/whyranoid/walkie/dto/WalkingDto.java
  src/main/java/com/whyranoid/walkie/dto/WalkingLikeDto.java
  src/main/java/com/whyranoid/walkie/repository/HistoryRepository.java
  src/main/java/com/whyranoid/walkie/repository/WalkieRepository.java
  src/main/java/com/whyranoid/walkie/repository/WalkingLikeRepository.java
  src/main/java/com/whyranoid/walkie/repository/querydsl/WalkingLikeRepositoryCustom.java
  src/main/java/com/whyranoid/walkie/repository/querydsl/WalkingLikeRepositoryImpl.java
  src/main/java/com/whyranoid/walkie/service/WalkingService.java
Labels: 병희, api
